engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- "lib/etcdv3/protos/*"
- "lib/etcdv3/etcdrpc/*"
