engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      	  mass_threshold: 30
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- "lib/etcdv3/protos/*"
- "lib/etcdv3/etcdrpc/*"
